language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: bin/phpunit

sudo: false
