sudo: false

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_TRAVISCI=phpcs

install: composer update

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - script/setup
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      script/cibuild-phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      script/cibuild-phpcs
    fi
